"""empty message

Revision ID: 5049e15f5957
Revises: 57c3331cd9d3
Create Date: 2022-04-26 09:51:59.079257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5049e15f5957'
down_revision = '57c3331cd9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'diration')
    op.add_column('tasks_categories', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_categories_catetory_id_fkey', 'tasks_categories', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_categories', 'categories', ['category_id'], ['_id'])
    op.drop_column('tasks_categories', 'catetory_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('catetory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.create_foreign_key('tasks_categories_catetory_id_fkey', 'tasks_categories', 'categories', ['catetory_id'], ['_id'])
    op.drop_column('tasks_categories', 'category_id')
    op.add_column('tasks', sa.Column('diration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'duration')
    # ### end Alembic commands ###
